apiVersion: v1
kind: Service
metadata:
  name: wine-classifier
  namespace: serving
  labels:
    app: wine-classifier
spec:
  type: ClusterIP
  selector:
    app: wine-classifier
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP